version: '3'

# Define the services/containers to be run
services:
	frontend: 
		hostname: localhost
		build: angular-nginx-frontend
		ports:
			- "4200:4200" 
		links:
			- backend

	backend:
		build: node-express-backend
		ports:
			- "3000:3000"
		links:
			- mongodb
		depends_on:
			- mongodb

	mongodb:
		image: mongo:latest
		ports:
			- "27017:27017"
		volumes:
			- database:/data/db

volumes:
	database: